[package]
name = "KaiYXBTC"
version = "0.0.1"
edition = "2024.beta"
published-at = "0xfc39a879b5a8772f682f1202cc5a8a3d93654cbb9e716b96bda7e5832af0e0eb"
 
[addresses]
kai_yxbtc = "0xfc39a879b5a8772f682f1202cc5a8a3d93654cbb9e716b96bda7e5832af0e0eb"
