[package]
name = "KaiSingleAssetVault"
edition = "2024.beta"
published-at = "0x909ad5f8badc34b49507dbd0cb9fb88cc816b531323659e3aefb992d4ab58474"

[dependencies]
WHUSDCE = { local = "../../../_vendor/whUSDCe" }
WHUSDTE = { local = "../../../_vendor/whUSDTe" }
ScallopProtocol = { local = "../../../_vendor/ScallopProtocol" }
ScallopPool = { local = "../../../_vendor/ScallopPool" }
KaiYwhUSDTeYSUI = { local = "../vault-token-init/kai-ywhusdte-ysui" }
AccessManagement = { local = "../../../access-management" }
KaiLeverage = { local = "../../leverage/core" }
rate_limiter = { local = "../../../rate-limiter" }

[addresses]
kai_sav = "0x01c389a85310b47e7630a9361d4e71025bc35e4999d3a645949b1b68b26f2273"
