[package]
name = "KaiLeverageSupplyPoolInitWbtc"
edition = "2024.beta"
license = "Apache 2.0"
authors = ["Kre≈°imir Klas (kklas@kunalabs.io)"]
published-at = "0x4acb21bc82d09db099d89a5cf48f433d34fbc46c04fc7b79dda0b27e7f32fb20"

[dependencies]
KaiLeverage = { local = "../../core" }
KaiLeverageSupplyPoolInit = { local = "../core" }
AccessManagement = { local = "../../../../access-management" }
wBTC = { local = "../../../../_vendor/wBTC" }

[addresses]
klsp_wbtc = "0x4acb21bc82d09db099d89a5cf48f433d34fbc46c04fc7b79dda0b27e7f32fb20"
