[package]
name = "KaiLeverageSupplyPoolInitLbtc"
edition = "2024.beta"
license = "Apache 2.0"
authors = ["Kre≈°imir Klas (kklas@kunalabs.io)"]
published-at = "0x390b72b290b407c1835c33442cbbdd68c24aeb84397ffdb953994456d020e2fd"

[dependencies]
KaiLeverage = { local = "../../core" }
KaiLeverageSupplyPoolInit = { local = "../core" }
AccessManagement = { local = "../../../../access-management" }
LBTC = { local = "../../../../_vendor/LBTC" }

[addresses]
klsp_lbtc = "0x390b72b290b407c1835c33442cbbdd68c24aeb84397ffdb953994456d020e2fd"
