[package]
name = "KaiLeverageSupplyPoolInitSui"
edition = "2024.beta"
license = "Apache 2.0"
authors = ["Kre≈°imir Klas (kklas@kunalabs.io)"]
published-at = "0x19163b40d52e67e20992f1b74c7376d30616ba966c8174e0990c58074d56eb8d"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.41.2", override = true }
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "mainnet-v1.41.2", override = true }
KaiLeverage = { local = "../../core" }
KaiLeverageSupplyPoolInit = { local = "../core" }

[addresses]
klsp_sui = "0x19163b40d52e67e20992f1b74c7376d30616ba966c8174e0990c58074d56eb8d"
