[package]
name = "KaiYWAL"
version = "0.0.1"
edition = "2024.beta"
published-at = "0xdab19711df7a4eefc633b9426e15d23305c6815eed775247e477599c706ede98"
 
[addresses]
kai_ywal = "0xdab19711df7a4eefc633b9426e15d23305c6815eed775247e477599c706ede98"
