[package]
name = "KaiLeverage"
license = "Apache 2.0"
authors = ["Kre≈°imir Klas (kklas@kunalabs.io)"]
edition = "2024.beta"
published-at = "0xd98a76e61b2499856e1958291b2c170a02e6c43d555d18f2f2f7d2741736481b"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.55.0", override = true }
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "mainnet-v1.55.0", override = true }
AccessManagement = { local = "../../../access-management" }
CetusClmm = { local = "../../../_vendor/CetusClmm" }
IntegerMate = { local = "../../../_vendor/IntegerMate", override = true }
Pyth = { local = "../../../_vendor/Pyth" }
WHUSDCE = { local = "../../../_vendor/whUSDCe" }
WHUSDTE = { local = "../../../_vendor/whUSDTe" }
usdc = { local = "../../../_vendor/USDC/usdc" }
bluefin_spot = { local = "../../../_vendor/bluefin_spot" }
rate_limiter = { local = "../../../rate-limiter" }
SuiUsdt = { local = "../../../_vendor/SuiUsdt" }
USDY = { local = "../../../_vendor/USDY" }
DEEP = { local = "../../../_vendor/DEEP" }
WAL = { local = "../../../_vendor/WAL" }
LBTC = { local = "../../../_vendor/LBTC" }
wBTC = { local = "../../../_vendor/wBTC" }
xBTC = { local = "../../../_vendor/xBTC" }

[addresses]
kai_leverage = "0x51e0ccce48f0763f98f1cb4856847c2e1531adacada99cdd7626ab999db57523"
